config/routes.rb
Rails.application.routes.draw do

  devise_for :sellers
  root 'site/static#home'
  get 'sellers/dashboard', as: 'seller_root'

  scope module: 'site' do
    resources :adverts
    resources :advert_categories

    resources :product_tags
    resources :tags
    resources :site_variables
    resources :static_pages
    resources :slides
    resources :sliders
    resources :orders

    resources :line_items do
      get 'increment_count', on: :member
      get 'decrement_count', on: :member 
    end 

    resources :carts
    resources :product_category_attacments
    resources :post_categories
    resources :posts
    resources :product_attacments
    resources :product_categories

    resources :products do
      resources :product_questions
      resources :mini_carts
    end
  end

  namespace :administrator do
    resources :products
    resources :product_categories
    resources :orders
    resources :posts
    resources :post_categories
    resources :sliders
    resources :slides
    resources :sellers
    resources :static_pages
    resources :site_variables
  end

  

  namespace :sellers do
    resources :products
    resources :orders
    resources :product_questions
    resources :product_tags
    resources :mini_carts

    resources :adverts do
      post 'set_active', on: :member
      post 'set_archive', on: :member
      resources :advert_positions
    end
  end

  get '/administrator', to: 'administrator#dashboard'

 

  match "/search" => "site/products#search", via: [ :get, :post ]

end

app/controllers/administrator/sellers_controller.rb
class Administrator::SellersController < AdministratorController
  
   before_action :set_seller, only: [:show, :edit, :update, :destroy]

  def index
    @sellers = Seller.all
   
  end

  def edit
    @seller = Seller.find(params[:id])
 
  end

    def new
    @seller = Seller.new    
    end

  # POST /seller
  # POST /seller.json
  def create
    @seller = Seller.create(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seller/1
  # PATCH/PUT /seller/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller/1
  # DELETE /seller/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def seller_params
      params.require(:seller).permit(:title, :content, :text, :content, :avatar,
        :seo_title, :seo_description, :seo_keywords, :to_main_page)
  end

  def set_seller
      @seller = Seller.find(params[:id])
    end

end

app/controllers/seller/advert_positions_controller.rb
class Seller::AdvertPositionsController < SellerController
  before_action :set_advert_position, only: [:destroy, :set_advert]
  before_action :set_advert, only: [:destroy]


  def new
    @advert_position = AdvertPosition.new
  end

  def create
   @advert_position = AdvertPosition.new(advert_position_params)
   @advert_position.advert_id = params[:advert_id]

    respond_to do |format|
      if @advert_position.save
        AddAndRemoveAdvertPositionToAdvert.new(@advert_position).add_position
        format.html { redirect_to :back, notice: 'success' }
      else
        format.html { redirect_to :back, notice: 'error' }
      end
    end
  end

  

  def destroy
    
    respond_to do |format|
      if @advert.active == false
        AddAndRemoveAdvertPositionToAdvert.new(@advert_position).remove_position
        @advert_position.destroy
        format.html { redirect_to :back, notice: 'Позиция удалена' }
      else
        format.html { redirect_to :back, notice: 'Ошибка, нельзя редактировать активное объявление' }
      end  
    end
    
  end

  private
    def set_advert_position
      @advert_position = AdvertPosition.find(params[:id])
    end

    def set_advert
      @advert = Advert.find(@advert_position.advert_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_position_params
      params[:advert_position].permit(:product_category_id, :place, :views, :time_days)
    end
end

app/controllers/seller/adverts_controller.rb
  class Seller::AdvertsController < SellerController

  before_action :set_advert, only: [:show, :edit, :update, :destroy, :set_active]
  before_action :set_seller, only: [:index, :edit, :update]


  def index
    @adverts            = Advert.all
    @active_adverts     = Advert.where(active: true)
    @no_active_adverts  = Advert.where(active: false)
    @archive_adverts     = Advert.where(archive: true)
    @advert             = Advert.new

    @product_categories = ProductCategory.all
    @products           = @seller.products.all

  end

  def edit
    @advert = Advert.find(params[:id])
    @product_categories = ProductCategory.all.collect {|category| ["#{category.name}    цена показа в категории: #{category.price_show_advert_in_category}$, цена за показ в товарах: #{category.price_show_advert_in_product}$", category.id ]}
    @advert_positions = AdvertPosition.where(advert_id: @advert.id)
    @product = Product.find(@advert.product_id)
    @product_category = @product.product_category
    @advert_position = AdvertPosition.new

    @current_seller = Seller.find(@advert.seller_id)

    render 'seller/adverts/edit'
  end

  def new
    @advert = Advert.new
  end

  def create
    @seller = Seller.first
    @advert = Advert.create(product_id: params[:advert][:product_id], seller_id: @seller.id)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to edit_seller_advert_path(@advert), notice: 'Информация обновлена' }
      else
        format.html { render :new }
      end
    end
  end


  def set_active
    respond_to do |format|
      if SetAdvertStatus.new(@advert).set_active == true
        format.html { redirect_to :back, notice: 'Объявление поставлено в очередь' }
      else
        format.html { redirect_to :back, notice: 'Ошибка, на Вашем счету не достаточно средств' }
      end  
    end
  end


  private

  def advert_params
    params.require(:advert).permit()
  end

  def set_advert
    @advert = Advert.find(params[:id])
  end

  def set_seller
    @seller = Seller.first
  end

end

app/controllers/sellers/advert_positions_controller.rb
class Sellers::AdvertPositionsController < SellersController
  before_action :set_advert_position, only: [:destroy, :set_advert]
  before_action :set_advert, only: [:destroy]


  def new
    @advert_position = AdvertPosition.new
  end

  def create
   @advert_position = AdvertPosition.new(advert_position_params)
   @advert_position.advert_id = params[:advert_id]

    respond_to do |format|
      if @advert_position.save
        AddAndRemoveAdvertPositionToAdvert.new(@advert_position).add_position
        format.html { redirect_to :back, notice: 'success' }
      else
        format.html { redirect_to :back, notice: 'error' }
      end
    end
  end

  

  def destroy
    
    respond_to do |format|
      if @advert.active == false
        AddAndRemoveAdvertPositionToAdvert.new(@advert_position).remove_position
        @advert_position.destroy
        format.html { redirect_to :back, notice: 'Позиция удалена' }
      else
        format.html { redirect_to :back, notice: 'Ошибка, нельзя редактировать активное объявление' }
      end  
    end
    
  end

  private
    def set_advert_position
      @advert_position = AdvertPosition.find(params[:id])
    end

    def set_advert
      @advert = Advert.find(@advert_position.advert_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_position_params
      params[:advert_position].permit(:product_category_id, :place, :views, :time_days)
    end
end

app/controllers/sellers/adverts_controller.rb
  class Sellers::AdvertsController < SellersController

  before_action :set_advert, only: [:show, :edit, :update, :destroy, :set_active]


  def index
    @adverts            = Advert.all
    @active_adverts     = Advert.where(active: true, seller_id: current_seller.id)
    @no_active_adverts  = Advert.where(active: false, archive: false, seller_id: current_seller.id)
    @archive_adverts    = Advert.where(archive: true, seller_id: current_seller.id)
    @advert             = Advert.new

    @product_categories = ProductCategory.all
    @products           = current_seller.products.where(archive: false)

  end

  def edit
    @advert = Advert.find(params[:id])
    @product_categories = ProductCategory.all.collect {|category| ["#{category.name}    цена показа в категории: #{category.price_show_advert_in_category}$, цена за показ в товарах: #{category.price_show_advert_in_product}$", category.id ]}
    @advert_positions = AdvertPosition.where(advert_id: @advert.id)
    @product = Product.find(@advert.product_id)
    @product_category = @product.product_category
    @advert_position = AdvertPosition.new

    @current_seller = current_seller

    render 'sellers/adverts/edit'
  end

  def new
    @advert = Advert.new
  end

  def create
    @advert = Advert.create(product_id: params[:advert][:product_id], seller_id: current_seller.id)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to edit_sellers_advert_path(@advert), notice: 'Информация обновлена' }
      else
        format.html { render :new }
      end
    end
  end


  def set_active
    respond_to do |format|
      if SetAdvertStatus.new(@advert).set_active == true
        format.html { redirect_to :back, notice: 'Объявление поставлено в очередь' }
      else
        format.html { redirect_to :back, notice: 'Ошибка, на Вашем счету не достаточно средств' }
      end  
    end
  end


  private

  def advert_params
    params.require(:advert).permit()
  end

  def set_advert
    @advert = Advert.find(params[:id])
  end

end

app/controllers/sellers/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sellers/mini_carts_controller.rb
class Sellers::MiniCartsController < SellersController

  before_action :set_mini_cart, only: [:destroy]


  def index
    @mini_carts = MiniCart.where(seller_id: current_seller.id)
  end


  private


  def set_mini_cart
    @mini_cart = MiniCart.find(params[:id])
  end

end

app/controllers/sellers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sellers/orders_controller.rb
class Sellers::OrdersController < SellersController

  before_action :set_order, only: [:edit, :update, :destroy, :delete]


  def index
    @orders = Order.paginate(:page => params[:page], :per_page => 10)
  end


  

  private

  def order_params
    params.require(:order).permit()

  end

  def set_order
    @order = Order.find(params[:id])
  end

end

app/controllers/sellers/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sellers/product_questions_controller.rb
class Sellers::ProductQuestionsController < SellersController

  before_action :set_product_question, only: [:show, :destroy, :delete]


  def index
    @product_questions = ProductQuestion.where(seller_id: current_seller.id, archive: false).paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @product_question.update_attribute(:viewed, true)
  end

  def destroy
    @product_question.update_attribute(:archive, true)
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Информация обновлена' }
    end
  end

  private

  def product_question_params
    params.require(:product_question).permit(:archive)
  end

  def set_product_question
    @product_question = ProductQuestion.find(params[:id])
  end

end

app/controllers/sellers/product_tags_controller.rb
class Sellers::ProductTagsController < SellersController

  before_action :set_product_tag, only: [:destroy]


  def destroy
    @product_tag.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Информация обновлена' }
    end
  end


  private


  def set_product_tag
    @product_tag = ProductTag.find(params[:id])
  end

end

app/controllers/sellers/products_controller.rb
class Sellers::ProductsController < SellersController

  before_action :set_product, only: [:edit, :update, :destroy, :delete]


  def index
    @products = Product.where(seller_id: current_seller.id, archive: false).paginate(:page => params[:page], :per_page => 20)

  end

  def edit
    @product = Product.find(params[:id])
    @product_attachments = ProductAttacment.where(product_id: @product.id)
    #@product_tags = @product.tags.all
    @product_tags = ProductTag.where(product_id: @product.id)

  end

  # GET /products/new
  def new
    @product = Product.new  
   # @product_attachments = @product.product_attachments.build
  end

  def create
    @product = Product.new(product_params)
    SellerProduct.new(@product, params, current_seller).create_product

    respond_to do |format|
      if @product.save
        format.html { redirect_to edit_sellers_product_path(@product) , notice: 'Товар добавлен' }
      else
        format.html { redirect_to :back , notice: 'Произошла ошибка' }
      end
    end  
  end

  def update
    @product.assign_attributes(product_params)
    SellerProduct.new(@product, params, current_seller).update_product
     
    respond_to do |format|
      if @product.save
        format.html { redirect_to :back , notice: 'Информация обновлена' }
      else
        format.html { redirect_to :back , notice: 'Произошла ошибка' }
      end
    end  
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    SellerProductDestroy.new(@product).destroy_product
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Товар удален' }
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :short_description, :avatar, :price, :old_price, :avability, :qty, :product_category_id,
     :seo_title, :seo_description, :seo_keywords)

  end

  def set_product
    @product = Product.friendly.find(params[:id])
  end

end

app/controllers/sellers/sessions_controller.rb
class Sellers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

    layout 'site'


  # GET /resource/sign_in
  def new

    super
  end

  # POST /resource/sign_in
#   def create
 #    super
     
  # end

  # DELETE /resource/sign_out
   #def destroy
    # super
    
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end






end

app/controllers/sellers/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/seller_edit.html.erb
 <div id="page_content">
        <div id="page_content_inner">
            <div class="uk-grid" data-uk-grid-margin data-uk-grid-match id="user_profile">
                <div class="uk-width-large-7-10">
                    <div class="md-card">
                        <div class="user_heading">
                            <div class="user_heading_menu" data-uk-dropdown>
                                <i class="md-icon material-icons md-icon-light">&#xE5D4;</i>
                                <div class="uk-dropdown uk-dropdown-flip uk-dropdown-small">
                                    <ul class="uk-nav">
                                        <li><a href="#">Редактировать профиль</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="user_heading_avatar">
                                <!-- <img src="<%= @seller.avatar.admin %>" alt="user avatar"/> -->
                            </div>
                            <div class="user_heading_content">
                                <h2 class="heading_b uk-margin-bottom"><span class="uk-text-truncate"><%= "#{@seller.name} #{@seller.surname}" %></span><span class="sub-heading"><%= "#{@seller.phone} | #{@seller.email} | #{@seller.skype}" %></span></h2>
                                <ul class="user_stats">
                                    <li>
                                        <h4 class="heading_a"><%= @seller.products.count %> <span class="sub-heading">Товаров</span></h4>
                                    </li>
                                    <li>
                                        <h4 class="heading_a">120 <span class="sub-heading">Продаж</span></h4>
                                    </li>
                                    <li>
                                        <h4 class="heading_a">1200 $<span class="sub-heading">Оборот с момента регистрации</span></h4>
                                    </li>
                                </ul>
                            </div>
                           
                        </div>
                        <div class="user_content">
                            <ul id="user_profile_tabs" class="uk-tab" data-uk-tab="{connect:'#user_profile_tabs_content', animation:'slide-horizontal'}">
                                <li class="uk-active"><a href="#">Контакты</a></li>
                                <li><a href="#">Активность</a></li>
                                <li><a href="#">Товары</a></li>
                            </ul>
                            <ul id="user_profile_tabs_content" class="uk-switcher uk-margin">
                                <li>
                                      <div class="uk-grid uk-margin-medium-top uk-margin-large-bottom" data-uk-grid-margin>
                                        <div class="uk-width-large-1-2">
                                
                                            <ul class="md-list md-list-addon">
                                                <li>
                                                    
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading"><%= @seller.email %></span>
                                                        <span class="uk-text-small uk-text-muted">Email</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading"><%= @seller.phone %></span>
                                                        <span class="uk-text-small uk-text-muted">Phone</span>
                                                    </div>
                                                </li>
                                                <li>
                                                   
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading"><%= @seller.skype %></span>
                                                        <span class="uk-text-small uk-text-muted">Skype</span>
                                                    </div>
                                                </li>
                                                
                                            </ul>
                                        </div>
                                        <div class="uk-width-large-1-2">
                                            <ul class="md-list">
                                                 <li>
                                                    
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading"><%= @seller.sity %></span>
                                                        <span class="uk-text-small uk-text-muted">Город</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading">ул. Октябрьская, д.1 </span>
                                                        <span class="uk-text-small uk-text-muted">Адрес</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    
                                                    <div class="md-list-content">
                                                        <span class="md-list-heading"><%= @seller.zip %></span>
                                                        <span class="uk-text-small uk-text-muted">Индекс</span>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                </li>
                                <li>
                                    <div class="timeline">
                                        <div class="timeline_item">
                                            <div class="timeline_icon timeline_icon_success"><i class="material-icons">&#xE85D;</i></div>
                                            <div class="timeline_date">
                                                09 <span>08</span>
                                            </div>
                                            <div class="timeline_content">Добавил товар  <a href="#"><strong>Товар 1</strong></a></div>
                                        </div>
                                        
                                        <div class="timeline_item">
                                            <div class="timeline_icon"><i class="material-icons">&#xE410;</i></div>
                                            <div class="timeline_date">
                                                08 <span>08</span>
                                            </div>
                                             <div class="timeline_content">Продал товар <a href="#"><strong>Товар 2</strong></a></div>
                                        </div>
                                        <div class="timeline_item">
                                            <div class="timeline_icon timeline_icon_primary"><i class="material-icons">&#xE0B9;</i></div>
                                            <div class="timeline_date">
                                               07 <span>08</span>
                                            </div>
                                            <div class="timeline_content">
                                                Задал в вопрос в поддержку <a href="#"><strong>Какой лимит товаров для пользователя ?</strong></a>
                                                <div class="timeline_content_addon">
                                                    <blockquote>
                                                        Приветствую, хотелось бы более подробно узнать о лимитах на количество товаров для каждого пользователя.
                                                    </blockquote>
                                                </div>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </li>
                                <li>
                                    <ul class="md-list">
                                        <% @seller.products.each do |product| %>
                                            <li>
                                                <div class="md-list-content">
                                                    <span class="md-list-heading"><a href="<%= product_category_product_path(product.product_category, product) %>"><%= product.name %></a></span>
                                                    <div class="uk-margin-small-top">
                                                    <span class="uk-margin-right">
                                                        <i class="material-icons">&#xE192;</i> <span class="uk-text-muted uk-text-small"><%= product.created_at.to_date %></span>
                                                    </span>
                                                    <span class="uk-margin-right">
                                                        <i class="material-icons">&#xE0B9;</i> <span class="uk-text-muted uk-text-small"><%= product.price %></span>
                                                    </span>
                                                    <span class="uk-margin-right">
                                                        <i class="material-icons">&#xE417;</i> <span class="uk-text-muted uk-text-small">24</span>
                                                    </span>
                                                    </div>
                                                </div>
                                            </li>
                                        <% end %>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="uk-width-large-3-10">
                    <div class="md-card" data-uk-sticky="{ top: 48, media: 960 }">
                        <div class="md-card-content">
                            <div class="uk-margin-medium-bottom">
                                <h3 class="heading_c uk-margin-bottom">Баланс</h3>
                                <ul class="md-list md-list-addon">
                                    
                                    <li>
                                        <div class="md-list-addon-element">
                                            <i class="md-list-addon-icon material-icons uk-text-success">&#xE88F;</i>
                                        </div>
                                        <div class="md-list-content">
                                            <span class="md-list-heading">Состояние счета</span>
                                            <span class="uk-text-small uk-text-muted uk-text-truncate">Текущий счет: $1200</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>