config/routes.rb
Rails.application.routes.draw do

  devise_for :sellers
  root 'site/static#home'
  get 'sellers/dashboard', as: 'seller_root'

  scope module: 'site' do
    resources :adverts
    resources :advert_categories

    resources :product_tags
    resources :tags
    resources :site_variables
    resources :static_pages
    resources :slides
    resources :sliders
    resources :orders

    resources :line_items do
      get 'increment_count', on: :member
      get 'decrement_count', on: :member 
    end 

    resources :carts
    resources :product_category_attacments
    resources :post_categories
    resources :posts
    resources :product_attacments
    resources :product_categories

    resources :products do
      resources :product_questions
      resources :mini_carts
    end
  end

  namespace :administrator do
    resources :products
    resources :product_categories
    resources :orders
    resources :posts
    resources :post_categories
    resources :sliders
    resources :slides
    resources :sellers
    resources :static_pages
    resources :site_variables
  end

  

  namespace :sellers do
    resources :products
    resources :orders
    resources :product_questions
    resources :product_tags
    resources :mini_carts

    resources :adverts do
      post 'set_active', on: :member
      post 'set_archive', on: :member
      resources :advert_positions
    end
  end

  get '/administrator', to: 'administrator#dashboard'

 

  match "/search" => "site/products#search", via: [ :get, :post ]

end

app/controllers/administrator/orders_controller.rb
class Administrator::OrdersController < AdministratorController

  before_action :set_order, only: [:edit, :update, :destroy, :delete]


  def index
    @orders = Order.paginate(:page => params[:page], :per_page => 10)
  end


  

  private

  def order_params
    params.require(:order).permit()

  end

  def set_order
    @order = Order.find(params[:id])
  end

end

app/controllers/administrator/post_categories_controller.rb
class Administrator::PostCategoriesController < AdministratorController
  
   before_action :set_post_category, only: [:show, :edit, :update, :destroy]

  def index
    @post_categories = PostCategory.all
    render 'administrator/post_categories/index'
  end

  def edit
    @post_category = PostCategory.find(params[:id])
    render 'administrator/post_categories/edit'
  end

    def new
      @post_category = PostCategory.new
    end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @post_category = PostCategory.new(post_category_params)

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to :back, notice: 'Product category was successfully created.' }
        format.json { render :index, status: :created, location: @post_category }
      else
        format.html { render :new }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    respond_to do |format|
      if @post_category.update(post_category_params)
        format.html { redirect_to :back, notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_category }
      else
        format.html { render :edit }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @post_category.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Категория удалена' }
      format.json { head :no_content }
    end
  end

  private

  def post_category_params
      params.require(:post_category).permit(:name, :description, :seo_title, :seo_description,
        :seo_keywords)
  end

  def set_post_category
      @post_category = PostCategory.find(params[:id])
  end

end

app/controllers/administrator/posts_controller.rb
class Administrator::PostsController < AdministratorController
  
   before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    render 'administrator/posts/index'
  end

  def edit
    @post = Post.find(params[:id])
    render 'administrator/posts/edit'
    end

    def new
    @post = Post.new
    
    end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/administrator/posts', notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to '/administrator/posts', notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/posts', notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
      params.require(:post).permit(:post_category_id, :name, :content, :lead, :to_main_page, :avatar, :seo_title, :seo_description,
        :seo_keywords)
  end

  def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/administrator/product_categories_controller.rb
class Administrator::ProductCategoriesController < AdministratorController

  before_action :set_product_category, only: [:edit, :update, :destroy, :delete]


  def index
    @product_categories = ProductCategory.paginate(:page => params[:page], :per_page => 10)
    render '/administrator/product_categories/index'
  end

  def edit
    @product_category = ProductCategory.find(params[:id])
    @product_category_attachments = ProductCategoryAttacment.where(product_category_id: @product_category.id)
   
  end

  # GET /product_categorys/new
  def new
    @product_category = ProductCategory.new
    
    # @product_category.product_category_attachments.build
  end



  # POST /product_categorys
  # POST /product_categorys.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    @product_category.assign_attributes(product_category_params)

    respond_to do |format|
      if @product_category.save

        if params[:images] != nil
          params[:images].each do |image|
            ProductCategoryAttacment.create(product_category_id: @product_category.id, image: image)
          end
        end
        format.html { redirect_to edit_administrator_product_category_path(@product_category) , notice: 'Запись добавлена' }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categorys/1
  # PATCH/PUT /product_categorys/1.json
  def update
    @product_category = ProductCategory.find(params[:id])
    @product_category.assign_attributes(product_category_params)

     

    respond_to do |format|
      if @product_category.save
        if params[:images] != nil
          params[:images].each do |image|
            ProductCategoryAttacment.create(product_category_id: @product_category.id, image: image)
          end
        end

        format.html { redirect_to :back , notice: 'Информация обновлена' }
        format.json { render :index, status: :ok, location: @product_category }
      else
        format.html { render :update }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categorys/1
  # DELETE /product_categorys/1.json
  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Проект удален' }
      format.json { head :no_content }
    end
  end

  private

  def product_category_params
    params.require(:product_category).permit(:name, :description, :avatar, :to_main_page, :product_category_id,
     :seo_title, :seo_description, :seo_keywords
    )

  end

  def set_product_category
    @product_category = ProductCategory.find(params[:id])
  end

end

app/controllers/administrator/products_controller.rb
class Administrator::ProductsController < AdministratorController

  before_action :set_product, only: [:edit, :update, :destroy, :delete]


  def index
    @products = Product.paginate(:page => params[:page], :per_page => 10)

  end

  def edit
    @product = Product.find(params[:id])
    @product_attachments = ProductAttacment.where(product_id: @product.id)

  end

  # GET /products/new
  def new
    @product = Product.new

    # @product_attachments = @product.product_attachments.build
  end



  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    @product.assign_attributes(product_params)

    respond_to do |format|
      if @product.save

        if params[:images] != nil
          params[:images].each do |image|
            ProductAttacment.create(product_id: @product.id, image: image)
          end
        end
        format.html { redirect_to edit_administrator_product_path(@product) , notice: 'Проект добавлен' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @product.assign_attributes(product_params)

    if params[:product][:tags_list] != nil
          params[:product][:tags_list].each do |id|
            ProductTag.create(product_id: @product.id, tag_id: id)
          end
        end


    respond_to do |format|
      if @product.save
        
        if params[:images] != nil
          params[:images].each do |image|
            ProductAttacment.create(product_id: @product.id, image: image)
          end
        end

        format.html { redirect_to :back , notice: params }
        format.json { render :index, status: :ok, location: @product }
      else
        format.html { render :update }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Проект удален' }
      format.json { head :no_content }
    end
  end

  

  def product_params
    params.require(:product).permit(:name, :description, :short_description, :avatar, :price, :old_price, :avability, :qty, 
      :to_main_page, :product_category_id, :seo_title, :seo_description, :seo_keywords, :sku, tags_list: [])

  end

  def set_product
    @product = Product.find(params[:id])
  end

end

app/controllers/administrator/sellers_controller.rb
class Administrator::SellersController < AdministratorController
  
   before_action :set_seller, only: [:show, :edit, :update, :destroy]

  def index
    @sellers = Seller.all
   
  end

  def edit
    @seller = Seller.find(params[:id])
 
  end

    def new
    @seller = Seller.new    
    end

  # POST /seller
  # POST /seller.json
  def create
    @seller = Seller.create(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seller/1
  # PATCH/PUT /seller/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller/1
  # DELETE /seller/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/seller', notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def seller_params
      params.require(:seller).permit(:title, :content, :text, :content, :avatar,
        :seo_title, :seo_description, :seo_keywords, :to_main_page)
  end

  def set_seller
      @seller = Seller.find(params[:id])
    end

end

app/controllers/administrator/site_variables_controller.rb
class Administrator::SiteVariablesController < AdministratorController
  
   before_action :set_site_variable, only: [:show, :edit, :update, :destroy]

  def index
    @site_variables = SiteVariable.all
    render 'administrator/site_variables/index'
  end

  def edit
    @site_variable = SiteVariable.find(params[:id])
    render 'administrator/site_variables/edit'
    end

    def new
    @site_variable = SiteVariable.new
    
    end

  # POST /site_variables
  # POST /site_variables.json
  def create
    @site_variable = SiteVariable.create(site_variable_params)

    respond_to do |format|
      if @site_variable.save
        format.html { redirect_to :back, notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @site_variable }
      else
        format.html { render :new }
        format.json { render json: @site_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_variables/1
  # PATCH/PUT /site_variables/1.json
  def update
    respond_to do |format|
      if @site_variable.update(site_variable_params)
        format.html { redirect_to :back, notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @site_variable }
      else
        format.html { render :edit }
        format.json { render json: @site_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_variables/1
  # DELETE /site_variables/1.json
  def destroy
    @site_variable.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def site_variable_params
      params.require(:site_variable).permit(:static_page_id, :name, :content, :descriptor)
  end

  def set_site_variable
      @site_variable = SiteVariable.find(params[:id])
    end

end

app/controllers/administrator/sliders_controller.rb
class Administrator::SlidersController < AdministratorController
  
   before_action :set_slider, only: [:show, :edit, :update, :destroy]

  def index
    @sliders = Slider.all
    render 'administrator/sliders/index'
  end

  def edit
    @slider = Slider.find(params[:id])
    render 'administrator/sliders/edit'
    end

    def new
    @slider = Slider.new
    
    end

  # POST /sliders
  # POST /sliders.json
  def create
    @slider = Slider.create(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to '/administrator/sliders', notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1
  # PATCH/PUT /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to '/administrator/sliders', notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.json
  def destroy
    @slider.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/sliders', notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def slider_params
      params.require(:slider).permit(:name, :descriptor)
  end

  def set_slider
      @slider = Slider.find(params[:id])
    end

end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController


	layout "administrator"

	def dashboard
		render "layouts/administrator/dashboard"
	end	
end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  before_action :set_post_category, only: [:show, :edit, :update, :destroy]

  def show
     #sidebar data
    @sidebar_product_categories = ProductCategory.where(to_category_sidebar: true)
    @sidebar_products           = Product.where(to_category_sidebar: true)
    @sidebar_banners            = Banner.where(to_category_sidebar: true)
    @sidebar_hot_products       = Product.where(hot_product: true)
  end


  private

    def set_post_category
      @post_category = PostCategory.friendly.find(params[:id])
    end
    
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/views/administrator/post_categories/edit.html.erb
<div id="page_content">
    <div id="page_heading">
        <h1 id="product_edit_name"><%= @post_category.name %></h1>
        <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn">ID: <%= @post_category.id %></span>
    </div>
    <div id="page_content_inner">
        <%= form_for([:administrator, @post_category], class: "uk-form-stacked", id: "product_edit_form", :multipart => true ) do |f| %>
        <div class="uk-grid uk-grid-medium" data-uk-grid-margin>
            <div class="uk-width-xLarge-2-10 uk-width-large-3-10">
                <div class="md-card">
                    
                    <div class="md-card-content">
                        <div class="uk-float-right">
                            <input type="checkbox" data-switchery checked name="product_edit_active_control" id="product_edit_active_control" />
                        </div>
                        <label class="uk-display-block uk-margin-small-top" for="product_edit_active_control">Отображать саитбаре</label>
                    </div>
                </div>
                
            </div>
            <div class="uk-width-xLarge-10-10  uk-width-large-10-10">
                <div class="md-card">
                    <div class="md-card-toolbar">
                        <h3 class="heading_a">Основная информация</h3>
                    </div>
                    

                    <div class="md-card-content">
                  
                    <div class="uk-grid">
                        <div class="uk-width-2-2">
                            <div class="uk-form-row">
                                <label>Название</label>
                                <%= f.text_field :name, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Описание</label>
                                <%= f.text_area :description, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                        </div>
                        
                    </div>
                </div>

                
            </div>

            <div class="md-card">
                <div class="md-card-content">
                    <h3 class="heading_a">SEO</h3>
                    <div class="uk-grid">
                        <div class="uk-width-2-2">
                            <div class="uk-form-row">
                                <label>Title</label>
                                <%= f.text_area :seo_title, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Description</label>
                                <%= f.text_area :seo_description, class: "md-input", cols: 20, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Keywords</label>
                                <%= f.text_area :seo_keywords, class: "md-input", cols: 20, rows: 4 %>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            </div>
        </div>
             <div class="md-fab-wrapper">
                <a class="md-btn" href="/administrator/post_categories/">Назад</a>
                <%= f.submit(class: "md-btn md-btn-success", value: "Обновить") %>
            </div>
        <% end %>
    </div>
</div>

app/views/administrator/post_categories/index.html.erb
<div id="page_content">
        <div id="page_content_inner">

            <h3 class="heading_b uk-margin-bottom">Категории записей</h3>

            <div class="md-card uk-margin-medium-bottom">
                <div class="md-card-content">
                    <div class="uk-overflow-container">
                        <table class="uk-table uk-table-hover">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Количество записей</th>
                                <th>Количество записей</th>
                            </tr>
                            </thead>
                            <tbody>
                            <% @post_categories.each do |category| %>
                                <tr>
                                    <td><%= link_to category.name, edit_administrator_post_category_path(category) %></td>
                                      
                                    <td><%= category.posts.count %></td>
                                    <td>
                                        <%= link_to "Удалить", administrator_post_category_path(category), method: :delete, data: { confirm: 'Удалить категорию ?' } %>
                                    </td>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

           
        </div>
    </div>

     <div class="md-fab-wrapper">
                <a class="md-btn md-btn-success" href="/administrator/post_categories/new">Добавить</a>
            </div>

app/views/administrator/post_categories/new.html.erb
<div id="page_content">
    <div id="page_heading">
        <h1 id="product_edit_name">Новая категория записей</h1>
    </div>
    <div id="page_content_inner">
        <%= form_for([:administrator, @post_category], class: "uk-form-stacked", id: "product_edit_form", :multipart => true ) do |f| %>
        <div class="uk-grid uk-grid-medium" data-uk-grid-margin>
            <div class="uk-width-xLarge-2-10 uk-width-large-3-10">
                <div class="md-card">
                    
                    <div class="md-card-content">
                        <div class="uk-float-right">
                            <input type="checkbox" data-switchery checked name="product_edit_active_control" id="product_edit_active_control" />
                        </div>
                        <label class="uk-display-block uk-margin-small-top" for="product_edit_active_control">Отображать саитбаре</label>
                    </div>
                </div>
                
            </div>
            <div class="uk-width-xLarge-10-10  uk-width-large-10-10">
                <div class="md-card">
                    <div class="md-card-toolbar">
                        <h3 class="heading_a">Основная информация</h3>
                    </div>
                    

                    <div class="md-card-content">
                  
                    <div class="uk-grid">
                        <div class="uk-width-2-2">
                            <div class="uk-form-row">
                                <label>Название</label>
                                <%= f.text_field :name, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Описание</label>
                                <%= f.text_area :description, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                            
                            
                        </div>
                        
                    </div>
                </div>

                </div>
                
            <div class="md-card">
                <div class="md-card-content">
                    <h3 class="heading_a">SEO</h3>
                    <div class="uk-grid">
                        <div class="uk-width-2-2">
                            <div class="uk-form-row">
                                <label>Title</label>
                                <%= f.text_area :seo_title, class: "md-input", cols: 30, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Description</label>
                                <%= f.text_area :seo_description, class: "md-input", cols: 20, rows: 4 %>
                            </div>
                            <div class="uk-form-row">
                                <label>Keywords</label>
                                <%= f.text_area :seo_keywords, class: "md-input", cols: 20, rows: 4 %>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            </div>
        </div>
             <div class="md-fab-wrapper">
                <a class="md-btn" href="/administrator/post_categories/">Назад</a>
                <%= f.submit(class: "md-btn md-btn-success", value: "Создать") %>
            </div>
        <% end %>
    </div>
</div>